// frontend/src/views/MistakeTagManage.vue
<template>
  <section>
    <div class="page-head">
      <h1>错误标签</h1>
      <el-button type="primary" @click="openCreate">新增标签</el-button>
    </div>

    <el-table :data="tags" border>
      <el-table-column prop="id" label="ID" width="80" />
      <el-table-column prop="name" label="标签名称" width="220" />
      <el-table-column prop="description" label="说明" />
      <el-table-column label="操作" width="180">
        <template #default="{ row }">
          <el-button size="small" @click="openEdit(row)">编辑</el-button>
          <el-button size="small" type="danger" @click="remove(row.id)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog v-model="dialogVisible" :title="form.id ? '编辑标签' : '新增标签'" width="520px">
      <el-form :model="form" label-width="90px">
        <el-form-item label="标签名称">
          <el-input v-model="form.name" maxlength="100" />
        </el-form-item>
        <el-form-item label="说明">
          <el-input v-model="form.description" type="textarea" :rows="4" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="save">保存</el-button>
      </template>
    </el-dialog>
  </section>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createMistakeTag, deleteMistakeTag, listMistakeTags, updateMistakeTag } from '../api/mistakeTag'

const tags = ref([])
const dialogVisible = ref(false)
const form = reactive({
  id: null,
  name: '',
  description: ''
})

const resetForm = () => {
  form.id = null
  form.name = ''
  form.description = ''
}

const load = async () => {
  const res = await listMistakeTags()
  tags.value = res.data
}

const openCreate = () => {
  resetForm()
  dialogVisible.value = true
}

const openEdit = (row) => {
  form.id = row.id
  form.name = row.name
  form.description = row.description
  dialogVisible.value = true
}

const save = async () => {
  if (!form.name?.trim()) {
    ElMessage.warning('请填写标签名称')
    return
  }
  const payload = {
    name: form.name.trim(),
    description: form.description
  }
  if (form.id) {
    await updateMistakeTag(form.id, payload)
  } else {
    await createMistakeTag(payload)
  }
  dialogVisible.value = false
  ElMessage.success('已保存')
  await load()
}

const remove = async (id) => {
  await ElMessageBox.confirm('删除后，新交易将不能再选择这个标签。确认删除？', '删除标签', {
    type: 'warning',
    confirmButtonText: '删除',
    cancelButtonText: '取消'
  })
  await deleteMistakeTag(id)
  ElMessage.success('已删除')
  await load()
}

onMounted(load)
</script>

// frontend/src/pages/MistakeTagManage/index.jsx
import React, { useEffect, useState } from 'react';
import { Button, Form, Input, Modal, Popconfirm, Space, Table, message } from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import { createMistakeTag, deleteMistakeTag, listMistakeTags, updateMistakeTag } from '../../api/mistakeTag';

export default function MistakeTagManage() {
  const [tags, setTags] = useState([]);
  const [loading, setLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [form] = Form.useForm();

  const loadData = async () => {
    setLoading(true);
    try {
      const res = await listMistakeTags();
      setTags(res || []);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleOpenModal = (record = null) => {
    if (record) {
      setEditingId(record.id);
      form.setFieldsValue(record);
    } else {
      setEditingId(null);
      form.resetFields();
    }
    setIsModalOpen(true);
  };

  const handleSave = async () => {
    try {
      const values = await form.validateFields();
      const payload = {
        name: values.name.trim(),
        description: values.description,
      };

      if (editingId) {
        await updateMistakeTag(editingId, payload);
        message.success('更新成功');
      } else {
        await createMistakeTag(payload);
        message.success('创建成功');
      }
      setIsModalOpen(false);
      await loadData();
    } catch (error) {
      // 表单校验失败或请求失败时，Antd/http 拦截器会处理提示。
    }
  };

  const handleDelete = async (id) => {
    try {
      await deleteMistakeTag(id);
      message.success('已删除');
      await loadData();
    } catch (error) {
      message.error('删除失败');
    }
  };

  const columns = [
    { title: 'ID', dataIndex: 'id', width: 80 },
    { title: '标签名称', dataIndex: 'name', width: 220 },
    { title: '说明', dataIndex: 'description' },
    {
      title: '操作',
      key: 'action',
      width: 180,
      render: (_, record) => (
        <Space size="middle">
          <Button type="link" onClick={() => handleOpenModal(record)} style={{ padding: 0 }}>
            编辑
          </Button>
          <Popconfirm
            title="删除标签"
            description="删除后，新交易将不能再选择这个标签。确认删除？"
            onConfirm={() => handleDelete(record.id)}
            okText="删除"
            cancelText="取消"
            okButtonProps={{ danger: true }}
          >
            <Button type="link" danger style={{ padding: 0 }}>
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
        <h2 style={{ margin: 0 }}>错误标签</h2>
        <Button type="primary" icon={<PlusOutlined />} onClick={() => handleOpenModal()}>
          新增标签
        </Button>
      </div>

      <Table rowKey="id" columns={columns} dataSource={tags} loading={loading} bordered pagination={false} />

      <Modal
        title={editingId ? '编辑标签' : '新增标签'}
        open={isModalOpen}
        onOk={handleSave}
        onCancel={() => setIsModalOpen(false)}
        destroyOnClose
      >
        <Form form={form} layout="vertical">
          <Form.Item name="name" label="标签名称" rules={[{ required: true, message: '请填写标签名称' }]}>
            <Input maxLength={100} />
          </Form.Item>
          <Form.Item name="description" label="说明">
            <Input.TextArea rows={4} />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
