// frontend/src/views/TradeDetail.vue
<template>
  <section>
    <div class="page-head">
      <h1>交易详情</h1>
      <div class="toolbar">
        <el-button @click="$router.push('/trades')">返回列表</el-button>
        <el-button type="primary" @click="$router.push(`/trades/edit/${route.params.id}`)">编辑交易</el-button>
        <el-button @click="$router.push(`/trades/${route.params.id}/review`)">写复盘</el-button>
      </div>
    </div>

    <el-empty v-if="!trade" description="暂无数据" />
    <div v-else class="detail-layout">
      <div class="panel">
        <div class="panel-title">基础信息</div>
        <div class="detail-grid">
          <div class="detail-item">
            <span>股票代码</span>
            <strong>{{ trade.stockCode || '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>股票名称</span>
            <strong>{{ trade.stockName || '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>是否模式内</span>
            <strong>{{ trade.isPatternTrade === 1 ? '是' : '否' }}</strong>
          </div>
        </div>
      </div>

      <div class="panel">
        <div class="panel-title">系统汇总</div>
        <div class="detail-grid">
          <div class="detail-item">
            <span>首次买入时间</span>
            <strong>{{ formatDateTime(trade.buyTime) }}</strong>
          </div>
          <div class="detail-item">
            <span>最后卖出时间</span>
            <strong>{{ formatDateTime(trade.sellTime) }}</strong>
          </div>
          <div class="detail-item">
            <span>平均买入价</span>
            <strong>{{ trade.avgBuyPrice ?? trade.buyPrice ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>平均卖出价</span>
            <strong>{{ trade.avgSellPrice ?? trade.sellPrice ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>累计买入数量</span>
            <strong>{{ trade.totalBuyQuantity ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>累计卖出数量</span>
            <strong>{{ trade.totalSellQuantity ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>剩余数量</span>
            <strong>{{ trade.remainingQuantity ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>持仓状态</span>
            <strong>{{ positionStatusText(trade.positionStatus) }}</strong>
          </div>
          <div class="detail-item">
            <span>统计归属日期</span>
            <strong>{{ trade.tradeDate || '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>盈亏金额</span>
            <strong>{{ trade.profitAmount ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>盈亏比例</span>
            <strong>{{ trade.profitRate ?? '-' }}</strong>
          </div>
        </div>
      </div>

      <TradeExecutionDetails :trade-id="route.params.id" @changed="loadTrade" />

      <div class="panel">
        <div class="panel-title">错误标签</div>
        <div class="tag-list">
          <el-tag v-for="tag in mistakeTagNames" :key="tag" type="warning">{{ tag }}</el-tag>
          <span v-if="!mistakeTagNames.length" class="empty-text">暂无标签</span>
        </div>
      </div>

      <div class="panel">
        <div class="panel-title">交易观察</div>
        <el-descriptions :column="1" border>
          <el-descriptions-item label="老周观点">{{ trade.teacherOpinion || '-' }}</el-descriptions-item>
          <el-descriptions-item label="关键价位 / 失效位">{{ trade.keyLevel || '-' }}</el-descriptions-item>
        </el-descriptions>
      </div>
    </div>
  </section>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { getTrade, listTradeMistakes } from '../api/trade'
import { listMistakeTags } from '../api/mistakeTag'
import TradeExecutionDetails from '../components/TradeExecutionDetails.vue'

const route = useRoute()
const trade = ref(null)
const mistakeTagIds = ref([])
const mistakeTagMap = ref({})

const mistakeTagNames = computed(() => mistakeTagIds.value.map((id) => mistakeTagMap.value[id]).filter(Boolean))

const formatDateTime = (value) => {
  if (!value) return '-'
  return String(value).replace('T', ' ')
}

const positionStatusText = (value) => {
  const map = {
    OPEN: 'OPEN',
    PARTIAL_CLOSED: 'PARTIAL_CLOSED',
    CLOSED: 'CLOSED'
  }
  return map[value] || '-'
}

const loadTrade = async () => {
  const res = await getTrade(route.params.id)
  trade.value = res.data
}

onMounted(async () => {
  const [tradeRes, mistakeRes, tagsRes] = await Promise.all([
    getTrade(route.params.id),
    listTradeMistakes(route.params.id),
    listMistakeTags()
  ])
  trade.value = tradeRes.data
  mistakeTagIds.value = mistakeRes.data
  mistakeTagMap.value = Object.fromEntries(tagsRes.data.map((tag) => [tag.id, tag.name]))
})
</script>

// frontend/src/pages/TradeDetail/index.jsx
import React, { useEffect, useState } from 'react';
import { Button, Card, Descriptions, Empty, Space, Spin, Tag } from 'antd';
import { EditOutlined, FileTextOutlined, LeftOutlined } from '@ant-design/icons';
import { useNavigate, useParams } from 'react-router-dom';
import { getTrade, listTradeMistakes } from '../../api/trade';
import { listMistakeTags } from '../../api/mistakeTag';
import TradeExecutionDetails from '../../components/TradeExecutionDetails';

const displayValue = (value) => (value === null || value === undefined || value === '' ? '-' : value);
const formatDateTime = (value) => (value ? String(value).replace('T', ' ') : '-');
const positionStatusText = (value) => value || '-';

const summaryItems = (trade) => [
  { label: '首次买入时间', children: formatDateTime(trade.buyTime) },
  { label: '最后卖出时间', children: formatDateTime(trade.sellTime) },
  { label: '平均买入价', children: displayValue(trade.avgBuyPrice ?? trade.buyPrice) },
  { label: '平均卖出价', children: displayValue(trade.avgSellPrice ?? trade.sellPrice) },
  { label: '累计买入数量', children: displayValue(trade.totalBuyQuantity) },
  { label: '累计卖出数量', children: displayValue(trade.totalSellQuantity) },
  { label: '剩余数量', children: displayValue(trade.remainingQuantity) },
  { label: '持仓状态', children: positionStatusText(trade.positionStatus) },
  { label: '统计归属日期', children: displayValue(trade.tradeDate) },
  { label: '盈亏金额', children: displayValue(trade.profitAmount) },
  { label: '盈亏比例', children: displayValue(trade.profitRate) },
];

export default function TradeDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [trade, setTrade] = useState(null);
  const [mistakeTagNames, setMistakeTagNames] = useState([]);
  const [loading, setLoading] = useState(true);

  const loadData = async () => {
    setLoading(true);
    try {
      const [tradeRes, mistakeIds, tags] = await Promise.all([
        getTrade(id),
        listTradeMistakes(id).catch(() => []),
        listMistakeTags(),
      ]);
      const tagMap = Object.fromEntries((tags || []).map((tag) => [tag.id, tag.name]));
      setTrade(tradeRes || null);
      setMistakeTagNames((mistakeIds || []).map((tagId) => tagMap[tagId]).filter(Boolean));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [id]);

  if (loading) {
    return (
      <div style={{ textAlign: 'center', padding: 50 }}>
        <Spin size="large" />
      </div>
    );
  }

  if (!trade) {
    return <Empty description="暂无数据" />;
  }

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
        <h2 style={{ margin: 0 }}>交易详情</h2>
        <Space>
          <Button icon={<LeftOutlined />} onClick={() => navigate('/trades')}>
            返回列表
          </Button>
          <Button type="primary" icon={<EditOutlined />} onClick={() => navigate(`/trades/edit/${id}`)}>
            编辑交易
          </Button>
          <Button icon={<FileTextOutlined />} onClick={() => navigate(`/trades/${id}/review`)}>
            写复盘
          </Button>
        </Space>
      </div>

      <Space direction="vertical" size={20} style={{ width: '100%' }}>
        <Card title="基础信息" bordered={false}>
          <Descriptions bordered column={3}>
            <Descriptions.Item label="股票代码">{displayValue(trade.stockCode)}</Descriptions.Item>
            <Descriptions.Item label="股票名称">{displayValue(trade.stockName)}</Descriptions.Item>
            <Descriptions.Item label="是否模式内">
              <Tag color={trade.isPatternTrade === 1 ? 'success' : 'error'}>{trade.isPatternTrade === 1 ? '是' : '否'}</Tag>
            </Descriptions.Item>
          </Descriptions>
        </Card>

        <Card title="系统汇总" bordered={false}>
          <Descriptions bordered column={3} items={summaryItems(trade)} />
        </Card>

        <Card bordered={false}>
          <TradeExecutionDetails tradeId={id} onChanged={loadData} />
        </Card>

        <Card title="错误标签" bordered={false}>
          {mistakeTagNames.length ? (
            <Space size={[6, 6]} wrap>
              {mistakeTagNames.map((tag) => (
                <Tag color="warning" key={tag}>
                  {tag}
                </Tag>
              ))}
            </Space>
          ) : (
            <span style={{ color: '#8c8c8c' }}>暂无标签</span>
          )}
        </Card>

        <Card title="交易观察" bordered={false}>
          <Descriptions bordered column={1}>
            <Descriptions.Item label="老周观点">{displayValue(trade.teacherOpinion)}</Descriptions.Item>
            <Descriptions.Item label="关键价位 / 失效位">{displayValue(trade.keyLevel)}</Descriptions.Item>
          </Descriptions>
        </Card>
      </Space>
    </div>
  );
}
