// frontend/src/pages/TradeForm/index.jsx
import React, { useEffect, useState } from 'react';
import { Button, Card, Col, Descriptions, Form, Input, Row, Select, Space, Spin, Switch, message } from 'antd';
import { LeftOutlined, SaveOutlined } from '@ant-design/icons';
import { useNavigate, useParams } from 'react-router-dom';
import {
  createTradeWithExecutionDetails,
  getTrade,
  listTradeMistakes,
  saveTradeMistakes,
  updateTrade,
} from '../../api/trade';
import { listMistakeTags } from '../../api/mistakeTag';
import TradeExecutionDetails from '../../components/TradeExecutionDetails';

const displayValue = (value) => (value === null || value === undefined || value === '' ? '-' : value);
const formatDateTime = (value) => (value ? String(value).replace('T', ' ') : '-');

const toExecutionPayload = (detail) => ({
  actionType: detail.actionType,
  executionTime: detail.executionTime,
  price: detail.price,
  quantity: detail.quantity,
  positionNote: detail.positionNote,
  reason: detail.reason,
  remark: detail.remark,
});

const summaryItems = (trade) => [
  { label: '首次买入时间', children: formatDateTime(trade.buyTime) },
  { label: '最后卖出时间', children: formatDateTime(trade.sellTime) },
  { label: '平均买入价', children: displayValue(trade.avgBuyPrice ?? trade.buyPrice) },
  { label: '平均卖出价', children: displayValue(trade.avgSellPrice ?? trade.sellPrice) },
  { label: '累计买入数量', children: displayValue(trade.totalBuyQuantity) },
  { label: '累计卖出数量', children: displayValue(trade.totalSellQuantity) },
  { label: '剩余数量', children: displayValue(trade.remainingQuantity) },
  { label: '持仓状态', children: displayValue(trade.positionStatus) },
  { label: '统计归属日期', children: displayValue(trade.tradeDate) },
  { label: '盈亏金额', children: displayValue(trade.profitAmount) },
  { label: '盈亏比例', children: displayValue(trade.profitRate) },
];

export default function TradeForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEdit = Boolean(id);
  const [form] = Form.useForm();
  const [trade, setTrade] = useState({});
  const [mistakeTags, setMistakeTags] = useState([]);
  const [draftExecutionDetails, setDraftExecutionDetails] = useState([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);

  const loadTrade = async () => {
    if (!isEdit) return;
    setLoading(true);
    try {
      const [tradeRes, mistakeIds] = await Promise.all([getTrade(id), listTradeMistakes(id)]);
      setTrade(tradeRes || {});
      form.setFieldsValue({
        stockCode: tradeRes?.stockCode,
        stockName: tradeRes?.stockName,
        isPatternTrade: tradeRes?.isPatternTrade !== 0,
        mistakeTagIds: mistakeIds || [],
        teacherOpinion: tradeRes?.teacherOpinion,
        keyLevel: tradeRes?.keyLevel,
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const loadInitialData = async () => {
      setLoading(true);
      try {
        const tags = await listMistakeTags();
        setMistakeTags(tags || []);
        if (isEdit) {
          await loadTrade();
        } else {
          form.setFieldsValue({ isPatternTrade: true, mistakeTagIds: [] });
        }
      } finally {
        setLoading(false);
      }
    };
    loadInitialData();
  }, [id]);

  const buildTradePayload = (values) => ({
    stockCode: values.stockCode,
    stockName: values.stockName,
    isPatternTrade: values.isPatternTrade ? 1 : 0,
    teacherOpinion: values.teacherOpinion,
    keyLevel: values.keyLevel,
  });

  const handleSave = async () => {
    setSaving(true);
    try {
      const values = await form.validateFields();
      if (isEdit) {
        await updateTrade(id, buildTradePayload(values));
        await saveTradeMistakes(id, values.mistakeTagIds || []);
        await loadTrade();
        message.success('交易基础信息已保存');
      } else {
        const createdTrade = await createTradeWithExecutionDetails({
          tradeRecord: buildTradePayload(values),
          mistakeTagIds: values.mistakeTagIds || [],
          executionDetails: draftExecutionDetails.map(toExecutionPayload),
        });
        message.success('交易和成交明细已保存');
        navigate(`/trades/edit/${createdTrade.id}`, { replace: true });
      }
    } catch (error) {
      if (!error?.errorFields) {
        message.error(error.response?.data?.message || error.message || '保存失败');
      }
    } finally {
      setSaving(false);
    }
  };

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
        <h2 style={{ margin: 0 }}>{isEdit ? '编辑交易' : '新增交易'}</h2>
        <Button icon={<LeftOutlined />} onClick={() => navigate('/trades')}>
          返回列表
        </Button>
      </div>

      <Spin spinning={loading}>
        <Space direction="vertical" size={20} style={{ width: '100%' }}>
          <Card title="交易基础信息" bordered={false}>
            <Form form={form} layout="vertical">
              <Row gutter={16}>
                <Col span={8}>
                  <Form.Item name="stockCode" label="股票代码" rules={[{ required: true, message: '请填写股票代码' }]}>
                    <Input />
                  </Form.Item>
                </Col>
                <Col span={8}>
                  <Form.Item name="stockName" label="股票名称" rules={[{ required: true, message: '请填写股票名称' }]}>
                    <Input />
                  </Form.Item>
                </Col>
                <Col span={8}>
                  <Form.Item name="isPatternTrade" label="模式内" valuePropName="checked">
                    <Switch checkedChildren="是" unCheckedChildren="否" />
                  </Form.Item>
                </Col>
              </Row>
              <Form.Item name="mistakeTagIds" label="错误标签">
                <Select
                  mode="multiple"
                  allowClear
                  placeholder="选择本笔交易的问题"
                  options={mistakeTags.map((tag) => ({ label: tag.name, value: tag.id }))}
                />
              </Form.Item>
              <Form.Item name="teacherOpinion" label="老周观点">
                <Input.TextArea rows={3} />
              </Form.Item>
              <Form.Item name="keyLevel" label="关键价位 / 失效位">
                <Input.TextArea rows={3} />
              </Form.Item>
              <Button type="primary" icon={<SaveOutlined />} loading={saving} onClick={handleSave}>
                保存
              </Button>
            </Form>
          </Card>

          <Card title="系统汇总" bordered={false}>
            <Descriptions bordered column={3} items={summaryItems(trade)} />
          </Card>

          <Card bordered={false}>
            {isEdit ? (
              <TradeExecutionDetails tradeId={id} onChanged={loadTrade} />
            ) : (
              <TradeExecutionDetails value={draftExecutionDetails} onChange={setDraftExecutionDetails} />
            )}
          </Card>
        </Space>
      </Spin>
    </div>
  );
}

// frontend/src/views/TradeForm.vue
<template>
  <section>
    <div class="page-head">
      <h1>{{ isEdit ? '编辑交易' : '新增交易' }}</h1>
      <el-button @click="$router.push('/trades')">返回列表</el-button>
    </div>

    <el-form :model="form" label-width="110px" class="form-panel">
      <div class="panel-title">交易基础信息</div>
      <el-row :gutter="16">
        <el-col :span="8"><el-form-item label="股票代码"><el-input v-model="form.stockCode" /></el-form-item></el-col>
        <el-col :span="8"><el-form-item label="股票名称"><el-input v-model="form.stockName" /></el-form-item></el-col>
        <el-col :span="8"><el-form-item label="模式内"><el-switch v-model="isPattern" /></el-form-item></el-col>
      </el-row>
      <el-form-item label="错误标签">
        <el-select v-model="mistakeTagIds" multiple clearable placeholder="选择本笔交易的问题">
          <el-option v-for="tag in mistakeTags" :key="tag.id" :label="tag.name" :value="tag.id" />
        </el-select>
      </el-form-item>
      <el-form-item label="老周观点"><el-input v-model="form.teacherOpinion" type="textarea" /></el-form-item>
      <el-form-item label="关键价位 / 失效位"><el-input v-model="form.keyLevel" type="textarea" /></el-form-item>
      <el-form-item>
        <el-button type="primary" @click="save">保存</el-button>
      </el-form-item>
    </el-form>

    <div class="detail-layout form-extra">
      <div class="panel">
        <div class="panel-title">系统汇总</div>
        <div class="detail-grid">
          <div class="detail-item">
            <span>首次买入时间</span>
            <strong>{{ formatDateTime(form.buyTime) }}</strong>
          </div>
          <div class="detail-item">
            <span>最后卖出时间</span>
            <strong>{{ formatDateTime(form.sellTime) }}</strong>
          </div>
          <div class="detail-item">
            <span>平均买入价</span>
            <strong>{{ form.avgBuyPrice ?? form.buyPrice ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>平均卖出价</span>
            <strong>{{ form.avgSellPrice ?? form.sellPrice ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>累计买入数量</span>
            <strong>{{ form.totalBuyQuantity ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>累计卖出数量</span>
            <strong>{{ form.totalSellQuantity ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>剩余数量</span>
            <strong>{{ form.remainingQuantity ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>持仓状态</span>
            <strong>{{ form.positionStatus || '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>统计归属日期</span>
            <strong>{{ form.tradeDate || '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>盈亏金额</span>
            <strong>{{ form.profitAmount ?? '-' }}</strong>
          </div>
          <div class="detail-item">
            <span>盈亏比例</span>
            <strong>{{ form.profitRate ?? '-' }}</strong>
          </div>
        </div>
      </div>

      <TradeExecutionDetails v-if="isEdit" :trade-id="route.params.id" @changed="loadTrade" />
      <TradeExecutionDetails v-else v-model="draftExecutionDetails" />
    </div>
  </section>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import {
  createTradeWithExecutionDetails,
  getTrade,
  listTradeMistakes,
  saveTradeMistakes,
  updateTrade
} from '../api/trade'
import { listMistakeTags } from '../api/mistakeTag'
import TradeExecutionDetails from '../components/TradeExecutionDetails.vue'

const route = useRoute()
const router = useRouter()
const isEdit = computed(() => Boolean(route.params.id))
const form = reactive({ isPatternTrade: 1 })
const mistakeTags = ref([])
const mistakeTagIds = ref([])
const draftExecutionDetails = ref([])
const isPattern = computed({
  get: () => form.isPatternTrade === 1,
  set: (value) => { form.isPatternTrade = value ? 1 : 0 }
})

const basePayload = () => ({
  stockCode: form.stockCode,
  stockName: form.stockName,
  isPatternTrade: form.isPatternTrade,
  teacherOpinion: form.teacherOpinion,
  keyLevel: form.keyLevel
})

const save = async () => {
  let tradeId = route.params.id
  if (isEdit.value) {
    await updateTrade(route.params.id, basePayload())
    await saveTradeMistakes(tradeId, mistakeTagIds.value)
    await loadTrade()
    ElMessage.success('交易基础信息已保存')
  } else {
    const res = await createTradeWithExecutionDetails({
      tradeRecord: basePayload(),
      mistakeTagIds: mistakeTagIds.value,
      executionDetails: draftExecutionDetails.value.map(toExecutionPayload)
    })
    tradeId = res.data.id
    Object.assign(form, res.data)
    draftExecutionDetails.value = []
    await router.replace(`/trades/edit/${tradeId}`)
    ElMessage.success('交易和成交明细已保存')
  }
}

const toExecutionPayload = (detail) => ({
  actionType: detail.actionType,
  executionTime: detail.executionTime,
  price: detail.price,
  quantity: detail.quantity,
  positionNote: detail.positionNote,
  reason: detail.reason,
  remark: detail.remark
})

const loadTrade = async () => {
  if (!route.params.id) return
  const [tradeRes, mistakesRes] = await Promise.all([
    getTrade(route.params.id),
    listTradeMistakes(route.params.id)
  ])
  Object.assign(form, tradeRes.data)
  mistakeTagIds.value = mistakesRes.data
}

const formatDateTime = (value) => {
  if (!value) return '-'
  return String(value).replace('T', ' ')
}

onMounted(async () => {
  const tagsRes = await listMistakeTags()
  mistakeTags.value = tagsRes.data
  if (isEdit.value) {
    await loadTrade()
  }
})
</script>
