// frontend/src/pages/WeeklyReview/index.jsx
import React, { useEffect, useState } from 'react';
import dayjs from 'dayjs';
import {
  Button,
  Card,
  Col,
  DatePicker,
  Descriptions,
  Form,
  Input,
  InputNumber,
  Row,
  Space,
  Table,
  message,
} from 'antd';
import { PlusOutlined, ReloadOutlined, SaveOutlined } from '@ant-design/icons';
import StatisticCard from '../../components/StatisticCard';
import { getWeekStatistics } from '../../api/statistics';
import {
  createWeeklyReview,
  getWeeklyReview,
  listWeeklyReviews,
  updateWeeklyReview,
} from '../../api/weeklyReview';

const { RangePicker } = DatePicker;

const weekRange = () => {
  const now = dayjs();
  const day = now.day() || 7;
  const start = now.subtract(day - 1, 'day');
  return [start, start.add(6, 'day')];
};

const emptyValues = {
  weekStart: null,
  weekEnd: null,
  startCapital: null,
  endCapital: null,
  profitAmount: null,
  profitRate: null,
  tradeCount: null,
  winCount: null,
  lossCount: null,
  winRate: null,
  patternTradeCount: null,
  nonPatternTradeCount: null,
  topMistakeSummary: '',
  biggestWinTrade: '',
  biggestLossTrade: '',
  profitSource: '',
  lossSource: '',
  biggestProblem: '',
  bestAction: '',
  ruleOne: '',
  ruleTwo: '',
  ruleThree: '',
  trainingTopic: '',
  trainingMethod: '',
  executionScore: null,
};

const displayValue = (value) => {
  if (value === null || value === undefined || value === '') return '-';
  return value;
};

const formatPercent = (value) => {
  if (value === null || value === undefined || value === '') return '-';
  return `${(Number(value) * 100).toFixed(1)}%`;
};

const formatMistakeSummary = (items = []) => {
  if (!items.length) return '';
  return items.map((item) => `${item.name}(${item.count})`).join(', ');
};

const toFormValues = (review = {}) => ({
  ...emptyValues,
  ...review,
  weekStart: review.weekStart ? dayjs(review.weekStart) : null,
  weekEnd: review.weekEnd ? dayjs(review.weekEnd) : null,
});

const toPayload = (values) => ({
  ...values,
  weekStart: values.weekStart ? values.weekStart.format('YYYY-MM-DD') : '',
  weekEnd: values.weekEnd ? values.weekEnd.format('YYYY-MM-DD') : '',
});

export default function WeeklyReview() {
  const [form] = Form.useForm();
  const [reviews, setReviews] = useState([]);
  const [currentId, setCurrentId] = useState(null);
  const [dateRange, setDateRange] = useState(weekRange());
  const [statisticsLoading, setStatisticsLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const watchedValues = {
    tradeCount: Form.useWatch('tradeCount', form),
    winCount: Form.useWatch('winCount', form),
    lossCount: Form.useWatch('lossCount', form),
    winRate: Form.useWatch('winRate', form),
    profitAmount: Form.useWatch('profitAmount', form),
    profitRate: Form.useWatch('profitRate', form),
    patternTradeCount: Form.useWatch('patternTradeCount', form),
    nonPatternTradeCount: Form.useWatch('nonPatternTradeCount', form),
    topMistakeSummary: Form.useWatch('topMistakeSummary', form),
    biggestWinTrade: Form.useWatch('biggestWinTrade', form),
    biggestLossTrade: Form.useWatch('biggestLossTrade', form),
    weekStart: Form.useWatch('weekStart', form),
    weekEnd: Form.useWatch('weekEnd', form),
  };

  const loadReviews = async () => {
    const res = await listWeeklyReviews();
    setReviews(res || []);
  };

  const applyStatistics = (stats = {}, range = dateRange) => {
    const [weekStart, weekEnd] = range;
    form.setFieldsValue({
      weekStart,
      weekEnd,
      tradeCount: stats.tradeCount ?? 0,
      winCount: stats.winCount ?? 0,
      lossCount: stats.lossCount ?? 0,
      winRate: stats.winRate ?? 0,
      profitAmount: stats.profitAmount ?? 0,
      profitRate: stats.profitRate ?? 0,
      patternTradeCount: stats.patternTradeCount ?? 0,
      nonPatternTradeCount: stats.nonPatternTradeCount ?? 0,
      topMistakeSummary: stats.topMistakeSummary || formatMistakeSummary(stats.topMistakes),
      biggestWinTrade: stats.biggestWinTrade || '',
      biggestLossTrade: stats.biggestLossTrade || '',
    });
  };

  const loadStatistics = async (range = dateRange) => {
    if (!range || range.length !== 2) {
      message.warning('请先选择日期范围');
      return;
    }
    const [start, end] = range;
    setStatisticsLoading(true);
    try {
      const stats = await getWeekStatistics({
        start: start.format('YYYY-MM-DD'),
        end: end.format('YYYY-MM-DD'),
      });
      applyStatistics(stats || {}, range);
    } finally {
      setStatisticsLoading(false);
    }
  };

  const resetForm = async () => {
    const range = weekRange();
    setCurrentId(null);
    setDateRange(range);
    form.setFieldsValue({ ...emptyValues, weekStart: range[0], weekEnd: range[1] });
    await loadStatistics(range);
  };

  const handleRangeChange = async (range) => {
    if (!range || range.length !== 2) {
      setDateRange([]);
      form.setFieldsValue({ weekStart: null, weekEnd: null });
      return;
    }
    setDateRange(range);
    form.setFieldsValue({ weekStart: range[0], weekEnd: range[1] });
    await loadStatistics(range);
  };

  const syncRangeFromForm = (nextValues) => {
    const values = { ...form.getFieldsValue(['weekStart', 'weekEnd']), ...nextValues };
    if (values.weekStart && values.weekEnd) {
      setDateRange([values.weekStart, values.weekEnd]);
    }
  };

  const loadReview = async (row) => {
    const review = await getWeeklyReview(row.id);
    setCurrentId(review.id);
    form.setFieldsValue(toFormValues(review));
    if (review.weekStart && review.weekEnd) {
      setDateRange([dayjs(review.weekStart), dayjs(review.weekEnd)]);
    }
  };

  const save = async () => {
    setSaving(true);
    try {
      const values = await form.validateFields();
      const payload = toPayload(values);
      if (!payload.weekStart || !payload.weekEnd) {
        message.warning('请先选择日期范围');
        return;
      }
      const saved = currentId
        ? await updateWeeklyReview(currentId, { ...payload, id: currentId })
        : await createWeeklyReview(payload);
      setCurrentId(saved.id);
      form.setFieldsValue(toFormValues(saved));
      if (saved.weekStart && saved.weekEnd) {
        setDateRange([dayjs(saved.weekStart), dayjs(saved.weekEnd)]);
      }
      await loadReviews();
      message.success('周复盘已保存');
    } catch (error) {
      if (!error?.errorFields) {
        message.error(error.response?.data?.message || error.message || '保存失败');
      }
    } finally {
      setSaving(false);
    }
  };

  useEffect(() => {
    const loadInitialData = async () => {
      const range = weekRange();
      setDateRange(range);
      form.setFieldsValue({ ...emptyValues, weekStart: range[0], weekEnd: range[1] });
      await Promise.all([loadReviews(), loadStatistics(range)]);
    };
    loadInitialData();
  }, []);

  const historyColumns = [
    { title: '开始', dataIndex: 'weekStart', width: 110 },
    { title: '结束', dataIndex: 'weekEnd', width: 110 },
    { title: '交易', dataIndex: 'tradeCount', width: 70 },
    { title: '评分', dataIndex: 'executionScore', width: 70 },
  ];

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, marginBottom: 20 }}>
        <h2 style={{ margin: 0 }}>周复盘</h2>
        <Space wrap>
          <RangePicker value={dateRange?.length === 2 ? dateRange : null} onChange={handleRangeChange} />
          <Button icon={<ReloadOutlined />} loading={statisticsLoading} onClick={() => loadStatistics()}>
            生成统计
          </Button>
          <Button icon={<PlusOutlined />} onClick={resetForm}>
            新建
          </Button>
          <Button type="primary" icon={<SaveOutlined />} loading={saving} onClick={save}>
            保存
          </Button>
        </Space>
      </div>

      <Row gutter={[20, 20]} align="top">
        <Col xs={24} xl={17}>
          <Space direction="vertical" size={20} style={{ width: '100%' }}>
            <Row gutter={[16, 16]}>
              <Col xs={24} md={12} xl={6}>
                <StatisticCard label="交易次数" value={displayValue(watchedValues.tradeCount)} />
              </Col>
              <Col xs={24} md={12} xl={6}>
                <StatisticCard
                  label="胜 / 负"
                  value={`${displayValue(watchedValues.winCount)} / ${displayValue(watchedValues.lossCount)}`}
                />
              </Col>
              <Col xs={24} md={12} xl={6}>
                <StatisticCard label="胜率" value={formatPercent(watchedValues.winRate)} />
              </Col>
              <Col xs={24} md={12} xl={6}>
                <StatisticCard
                  label="模式内 / 外"
                  value={`${displayValue(watchedValues.patternTradeCount)} / ${displayValue(watchedValues.nonPatternTradeCount)}`}
                />
              </Col>
              <Col xs={24} md={12} xl={6}>
                <StatisticCard label="周期盈亏" value={displayValue(watchedValues.profitAmount)} />
              </Col>
              <Col xs={24} md={12} xl={6}>
                <StatisticCard label="收益率" value={formatPercent(watchedValues.profitRate)} />
              </Col>
              <Col xs={24} md={12} xl={6}>
                <StatisticCard label="最大盈利" value={watchedValues.biggestWinTrade || '-'} />
              </Col>
              <Col xs={24} md={12} xl={6}>
                <StatisticCard label="最大亏损" value={watchedValues.biggestLossTrade || '-'} />
              </Col>
            </Row>

            <Card title="统计快照" bordered={false}>
              <Descriptions bordered column={2}>
                <Descriptions.Item label="错误排行">{watchedValues.topMistakeSummary || '-'}</Descriptions.Item>
                <Descriptions.Item label="统计周期">
                  {watchedValues.weekStart ? watchedValues.weekStart.format('YYYY-MM-DD') : '-'} 至{' '}
                  {watchedValues.weekEnd ? watchedValues.weekEnd.format('YYYY-MM-DD') : '-'}
                </Descriptions.Item>
              </Descriptions>
            </Card>

            <Card bordered={false}>
              <Form form={form} layout="vertical">
                <Row gutter={16}>
                  <Col xs={24} md={8}>
                    <Form.Item name="weekStart" label="周开始" rules={[{ required: true, message: '请选择周开始' }]}>
                      <DatePicker
                        style={{ width: '100%' }}
                        onChange={(value) => syncRangeFromForm({ weekStart: value })}
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={8}>
                    <Form.Item name="weekEnd" label="周结束" rules={[{ required: true, message: '请选择周结束' }]}>
                      <DatePicker
                        style={{ width: '100%' }}
                        onChange={(value) => syncRangeFromForm({ weekEnd: value })}
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={8}>
                    <Form.Item name="executionScore" label="执行评分">
                      <InputNumber min={0} max={10} style={{ width: '100%' }} />
                    </Form.Item>
                  </Col>
                </Row>
                <Form.Item name="profitSource" label="赚钱来源">
                  <Input.TextArea rows={3} />
                </Form.Item>
                <Form.Item name="lossSource" label="亏钱来源">
                  <Input.TextArea rows={3} />
                </Form.Item>
                <Form.Item name="biggestProblem" label="最大问题">
                  <Input.TextArea rows={3} />
                </Form.Item>
                <Form.Item name="bestAction" label="做得最好">
                  <Input.TextArea rows={3} />
                </Form.Item>
                <Form.Item name="ruleOne" label="纪律一">
                  <Input maxLength={30} />
                </Form.Item>
                <Form.Item name="ruleTwo" label="纪律二">
                  <Input maxLength={30} />
                </Form.Item>
                <Form.Item name="ruleThree" label="纪律三">
                  <Input maxLength={30} />
                </Form.Item>
                <Form.Item name="trainingTopic" label="训练主题">
                  <Input />
                </Form.Item>
                <Form.Item name="trainingMethod" label="训练方式">
                  <Input.TextArea rows={3} />
                </Form.Item>
              </Form>
            </Card>
          </Space>
        </Col>

        <Col xs={24} xl={7}>
          <Card title="历史周复盘" bordered={false}>
            <Table
              rowKey="id"
              columns={historyColumns}
              dataSource={reviews}
              size="small"
              pagination={false}
              onRow={(record) => ({ onClick: () => loadReview(record) })}
            />
          </Card>
        </Col>
      </Row>
    </div>
  );
}

// frontend/src/views/WeeklyReview.vue
<template>
  <section>
    <div class="page-head">
      <h1>周复盘</h1>
      <div class="toolbar">
        <el-date-picker
          v-model="dateRange"
          type="daterange"
          range-separator="至"
          start-placeholder="开始日期"
          end-placeholder="结束日期"
          value-format="YYYY-MM-DD"
          @change="handleRangeChange"
        />
        <el-button :loading="statisticsLoading" @click="loadStatistics">生成统计</el-button>
        <el-button @click="resetForm">新建</el-button>
        <el-button type="primary" :loading="saving" @click="save">保存</el-button>
      </div>
    </div>

    <div class="weekly-layout">
      <div class="weekly-main">
        <div class="stats-grid weekly-stats">
          <StatisticCard label="交易次数" :value="displayValue(form.tradeCount)" />
          <StatisticCard label="胜 / 负" :value="`${displayValue(form.winCount)} / ${displayValue(form.lossCount)}`" />
          <StatisticCard label="胜率" :value="formatPercent(form.winRate)" />
          <StatisticCard label="模式内 / 外" :value="`${displayValue(form.patternTradeCount)} / ${displayValue(form.nonPatternTradeCount)}`" />
          <StatisticCard label="周期盈亏" :value="displayValue(form.profitAmount)" />
          <StatisticCard label="收益率" :value="formatPercent(form.profitRate)" />
          <StatisticCard label="最大盈利" :value="form.biggestWinTrade || '-'" />
          <StatisticCard label="最大亏损" :value="form.biggestLossTrade || '-'" />
        </div>

        <div class="panel weekly-snapshot">
          <div class="panel-title">统计快照</div>
          <el-descriptions :column="2" border>
            <el-descriptions-item label="错误排行">{{ form.topMistakeSummary || '-' }}</el-descriptions-item>
            <el-descriptions-item label="统计周期">{{ form.weekStart || '-' }} 至 {{ form.weekEnd || '-' }}</el-descriptions-item>
          </el-descriptions>
        </div>

        <el-form :model="form" label-width="130px" class="form-panel">
          <el-row :gutter="16">
            <el-col :span="8">
              <el-form-item label="周开始">
                <el-date-picker v-model="form.weekStart" value-format="YYYY-MM-DD" @change="syncRangeFromForm" />
              </el-form-item>
            </el-col>
            <el-col :span="8">
              <el-form-item label="周结束">
                <el-date-picker v-model="form.weekEnd" value-format="YYYY-MM-DD" @change="syncRangeFromForm" />
              </el-form-item>
            </el-col>
            <el-col :span="8">
              <el-form-item label="执行评分">
                <el-input-number v-model="form.executionScore" :min="0" :max="10" />
              </el-form-item>
            </el-col>
          </el-row>
          <el-form-item label="赚钱来源"><el-input v-model="form.profitSource" type="textarea" /></el-form-item>
          <el-form-item label="亏钱来源"><el-input v-model="form.lossSource" type="textarea" /></el-form-item>
          <el-form-item label="最大问题"><el-input v-model="form.biggestProblem" type="textarea" /></el-form-item>
          <el-form-item label="做得最好"><el-input v-model="form.bestAction" type="textarea" /></el-form-item>
          <el-form-item label="纪律一"><el-input v-model="form.ruleOne" maxlength="30" /></el-form-item>
          <el-form-item label="纪律二"><el-input v-model="form.ruleTwo" maxlength="30" /></el-form-item>
          <el-form-item label="纪律三"><el-input v-model="form.ruleThree" maxlength="30" /></el-form-item>
          <el-form-item label="训练主题"><el-input v-model="form.trainingTopic" /></el-form-item>
          <el-form-item label="训练方式"><el-input v-model="form.trainingMethod" type="textarea" /></el-form-item>
        </el-form>
      </div>

      <div class="panel weekly-history">
        <div class="panel-title">历史周复盘</div>
        <el-table :data="reviews" size="small" highlight-current-row @row-click="loadReview">
          <el-table-column prop="weekStart" label="开始" width="100" />
          <el-table-column prop="weekEnd" label="结束" width="100" />
          <el-table-column prop="tradeCount" label="交易" width="70" />
          <el-table-column prop="executionScore" label="评分" width="70" />
        </el-table>
      </div>
    </div>
  </section>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import StatisticCard from '../components/StatisticCard.vue'
import { getWeekStatistics } from '../api/statistics'
import {
  createWeeklyReview,
  getWeeklyReview,
  listWeeklyReviews,
  updateWeeklyReview
} from '../api/weeklyReview'

const emptyForm = () => ({
  id: null,
  weekStart: '',
  weekEnd: '',
  startCapital: null,
  endCapital: null,
  profitAmount: null,
  profitRate: null,
  tradeCount: null,
  winCount: null,
  lossCount: null,
  winRate: null,
  patternTradeCount: null,
  nonPatternTradeCount: null,
  topMistakeSummary: '',
  biggestWinTrade: '',
  biggestLossTrade: '',
  profitSource: '',
  lossSource: '',
  biggestProblem: '',
  bestAction: '',
  ruleOne: '',
  ruleTwo: '',
  ruleThree: '',
  trainingTopic: '',
  trainingMethod: '',
  executionScore: null
})

const form = reactive(emptyForm())
const dateRange = ref([])
const reviews = ref([])
const statisticsLoading = ref(false)
const saving = ref(false)

const weekRange = () => {
  const now = new Date()
  const day = now.getDay() || 7
  const start = new Date(now)
  start.setDate(now.getDate() - day + 1)
  const end = new Date(start)
  end.setDate(start.getDate() + 6)
  return [formatDate(start), formatDate(end)]
}

const formatDate = (date) => {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

const resetForm = async () => {
  Object.assign(form, emptyForm())
  dateRange.value = weekRange()
  form.weekStart = dateRange.value[0]
  form.weekEnd = dateRange.value[1]
  await loadStatistics()
}

const syncRangeFromForm = () => {
  dateRange.value = form.weekStart && form.weekEnd ? [form.weekStart, form.weekEnd] : []
}

const handleRangeChange = async (range) => {
  if (!range || range.length !== 2) return
  form.weekStart = range[0]
  form.weekEnd = range[1]
  await loadStatistics()
}

const loadReviews = async () => {
  const res = await listWeeklyReviews()
  reviews.value = res.data || []
}

const loadReview = async (row) => {
  const res = await getWeeklyReview(row.id)
  Object.assign(form, emptyForm(), res.data)
  syncRangeFromForm()
}

const loadStatistics = async () => {
  if (!form.weekStart || !form.weekEnd) {
    ElMessage.warning('请先选择日期范围')
    return
  }
  statisticsLoading.value = true
  try {
    const res = await getWeekStatistics({ start: form.weekStart, end: form.weekEnd })
    applyStatistics(res.data || {})
  } finally {
    statisticsLoading.value = false
  }
}

const applyStatistics = (stats) => {
  form.tradeCount = stats.tradeCount ?? 0
  form.winCount = stats.winCount ?? 0
  form.lossCount = stats.lossCount ?? 0
  form.winRate = stats.winRate ?? 0
  form.profitAmount = stats.profitAmount ?? 0
  form.profitRate = stats.profitRate ?? 0
  form.patternTradeCount = stats.patternTradeCount ?? 0
  form.nonPatternTradeCount = stats.nonPatternTradeCount ?? 0
  form.topMistakeSummary = stats.topMistakeSummary || formatMistakeSummary(stats.topMistakes)
  form.biggestWinTrade = stats.biggestWinTrade || ''
  form.biggestLossTrade = stats.biggestLossTrade || ''
}

const formatMistakeSummary = (items = []) => {
  if (!items.length) return ''
  return items.map((item) => `${item.name}(${item.count})`).join(', ')
}

const save = async () => {
  if (!form.weekStart || !form.weekEnd) {
    ElMessage.warning('请先选择日期范围')
    return
  }
  if (form.tradeCount === null) {
    await loadStatistics()
  }
  saving.value = true
  try {
    const payload = { ...form }
    const res = form.id
      ? await updateWeeklyReview(form.id, payload)
      : await createWeeklyReview(payload)
    Object.assign(form, emptyForm(), res.data)
    syncRangeFromForm()
    await loadReviews()
    ElMessage.success('周复盘已保存')
  } finally {
    saving.value = false
  }
}

const displayValue = (value) => {
  if (value === null || value === undefined || value === '') return '-'
  return value
}

const formatPercent = (value) => {
  if (value === null || value === undefined || value === '') return '-'
  return `${(Number(value) * 100).toFixed(1)}%`
}

onMounted(async () => {
  await Promise.all([resetForm(), loadReviews()])
})
</script>
